apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pizza-ordering-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MepCity/pizza-ordering-service.git
    targetRevision: main
    path: charts/pizza-ordering-service
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
