# ArgoCD Application: GitOps ile otomatik deploy (bonus)
# GitHub'daki main branch değişince ArgoCD otomatik K8s'e deploy eder
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pizza-ordering-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MepCity/pizza-ordering-service.git
    targetRevision: main          # main branch'i takip et
    path: charts/pizza-ordering-service  # Helm chart burada
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true      # Git'te silinenleri K8s'den de sil
      selfHeal: true   # K8s'de manuel değişiklik olursa Git'e geri döndür
