apiVersion: v1
kind: ConfigMap
metadata:
  name: pizza-ordering-config
data:
  DATABASE_URL: "sqlite:///./pizza.db"
  S3_ARCHIVE_ENABLED: "false"
  S3_BUCKET_NAME: "pizza-orders"
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT_URL: "http://localstack:4566"
