apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pizza-ordering-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "pizza-ordering-service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "pizza-ordering-service.fullname" . }}
    spec:
      containers:
        - name: pizza-ordering-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "pizza-ordering-service.fullname" . }}-config
            - secretRef:
                name: {{ include "pizza-ordering-service.fullname" . }}-secret
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
