apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pizza-ordering-service.fullname" . }}-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secret.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.awsSecretAccessKey | quote }}
